-- CreateTable
CREATE TABLE `Lead` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fname` VARCHAR(191) NOT NULL,
    `lname` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `mobile` VARCHAR(191) NULL,
    `homePhone` VARCHAR(191) NULL,
    `otherPhone` VARCHAR(191) NULL,
    `status` VARCHAR(191) NULL,
    `emailOpt` BOOLEAN NULL,
    `address1` VARCHAR(191) NULL,
    `address2` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `postalCode` VARCHAR(191) NULL,
    `descrip` VARCHAR(191) NULL,
    `customDescrip` VARCHAR(191) NULL,
    `regularPro` BOOLEAN NULL,
    `enrich` BOOLEAN NULL,
    `homeSchool` BOOLEAN NULL,
    `examPrep` BOOLEAN NULL,
    `home` BOOLEAN NULL,
    `summerPro` BOOLEAN NULL,
    `assessOnly` BOOLEAN NULL,
    `other` BOOLEAN NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `Lead_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Student` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `parent_id` INTEGER NOT NULL,
    `fname` VARCHAR(191) NOT NULL,
    `lname` VARCHAR(191) NOT NULL,
    `year` VARCHAR(191) NULL,
    `schoolYear` VARCHAR(191) NULL,
    `school` VARCHAR(191) NULL,
    `teacher` VARCHAR(191) NULL,
    `gender` VARCHAR(191) NULL,
    `birth` VARCHAR(191) NULL,
    `account` VARCHAR(191) NULL,
    `virCen` VARCHAR(191) NULL,
    `descript` VARCHAR(191) NULL,
    `medicInfo` VARCHAR(191) NULL,
    `cenDir` VARCHAR(191) NULL,
    `subMat` VARCHAR(191) NULL,
    `stuNote` VARCHAR(191) NULL,
    `mediaRele` BOOLEAN NULL,
    `leaveUnder` BOOLEAN NULL,
    `contactTeach` BOOLEAN NULL,
    `scholarShip` BOOLEAN NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
